import { WorkflowNode } from '../types/workflow';

export const DEFAULT_NODES: WorkflowNode[] = [
  {
    id: 'segmentation',
    type: 'process',
    label: 'Segmentation',
    chineseLabel: '文本分段',
    status: 'succeeded',
    summary: '12 segments identified',
    updatedAt: '2026-04-11 10:00:00',
    dependencies: [],
  },
  {
    id: 'outline',
    type: 'process',
    label: 'Outline',
    chineseLabel: '提炼大纲',
    status: 'succeeded',
    summary: 'Structure validated',
    updatedAt: '2026-04-11 10:01:00',
    dependencies: [],
  },
  {
    id: 'character_sheet',
    type: 'process',
    label: 'Character Sheet',
    chineseLabel: '人物表',
    status: 'succeeded',
    summary: '3 main entities defined',
    updatedAt: '2026-04-11 10:02:00',
    dependencies: [],
  },
  {
    id: 'script',
    type: 'process',
    label: 'Script',
    chineseLabel: '分镜脚本',
    status: 'running',
    progress: 45,
    summary: 'Processing segment 4/12',
    updatedAt: '2026-04-11 10:05:00',
    dependencies: ['segmentation', 'outline', 'character_sheet'],
  },
  {
    id: 'character_image',
    type: 'process',
    label: 'Character Image',
    chineseLabel: '人物参考图',
    status: 'ready',
    summary: 'Pending upstream...',
    updatedAt: '2026-04-11 10:02:00',
    dependencies: ['character_sheet'],
  },
  {
    id: 'tts',
    type: 'process',
    label: 'TTS',
    chineseLabel: '配音生成',
    status: 'pending',
    summary: 'Waiting for segmentation',
    updatedAt: '2026-04-11 10:00:00',
    dependencies: ['segmentation'],
  },
  {
    id: 'image',
    type: 'process',
    label: 'Image',
    chineseLabel: '分镜图',
    status: 'pending',
    summary: 'Waiting for script',
    updatedAt: '2026-04-11 10:05:00',
    dependencies: ['script', 'character_image'],
  },
  {
    id: 'shot_video',
    type: 'process',
    label: 'Shot Video',
    chineseLabel: '分镜视频',
    status: 'pending',
    summary: 'Waiting for images',
    updatedAt: '2026-04-11 10:05:00',
    dependencies: ['image'],
  },
  {
    id: 'video',
    type: 'process',
    label: 'Final Video',
    chineseLabel: '视频合成',
    status: 'pending',
    summary: 'Final assembly',
    updatedAt: '2026-04-11 10:05:00',
    dependencies: ['tts', 'shot_video'],
  },
];

export const VOICE_PRESETS = [
  { id: 'male_calm', name: '男_沉稳青年音', description: '适合叙事、解说' },
  { id: 'male_strong', name: '男_王明军', description: '浑厚有力，适合史诗' },
  { id: 'female_explainer', name: '女_解说小美', description: '亲切自然，适合科普' },
  { id: 'female_documentary', name: '女_专题片配音', description: '端庄大气' },
  { id: 'boy', name: '正太', description: '活泼可爱' },
];

export const IMAGE_STYLES = [
  { id: 'realistic', name: '写实风格', description: '电影感真实光影' },
  { id: 'gongbi', name: '现代工笔人物', description: '传统韵味与现代结合' },
];
